apiVersion: apps/v1
kind: Deployment
metadata:
  name: twito-celery
  labels:
    app: twito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twito
  template:
    metadata:
      labels:
        app: twito
    spec:
      containers:
      - name: twito-celery
        image: twito
        env:
          - name: APP_ENV
            value: celery
          - name: DB_URL
            value: /db/twito.sqlite3
          - name: DMI_TCAT_USERNAME
            valueFrom:
              secretKeyRef:
                name: dmi-tcat-credentials
                key: username
          - name: DMI_TCAT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dmi-tcat-credentials
                key: password
          - name: SECRET_DB_NAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: name
          - name: SECRET_DB_USERNAME
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: username
          - name: SECRET_DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: db-credentials
                key: password
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: password
