apiVersion: apps/v1
kind: Deployment
metadata:
  name: twito-celery
  labels:
    app: twito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twito
  template:
    metadata:
      labels:
        app: twito
    spec:
      containers:
      - name: twito-celery
        image: twito
        env:
          - name: APP_ENV
            value: celery
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: password
        envFrom:
          - secretRef:
              name: db-credentials
