apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twito-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - api.skoraj.twito.si
    secretName: twito-tls
  rules:
  - host: api.skoraj.twito.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twito
            port:
              number: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twito-frontend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - skoraj.twito.si
    secretName: twito-frontend-tls
  rules:
  - host: skoraj.twito.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twito-frontend
            port:
              number: 80
