apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: twito-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  tls:
  - hosts:
    - twito.k8s.djnd.si
    secretName: twito-tls
  rules:
  - host: twito.k8s.djnd.si
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: twito
            port:
              number: 80
