
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito-staging
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '99b40b77d1749a4b29c2fb39da82f31d1b8584f9'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '99b40b77d1749a4b29c2fb39da82f31d1b8584f9'
