
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito-staging
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '05726dc9a572741c94cbe8b5e15ec90419de8b63'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '05726dc9a572741c94cbe8b5e15ec90419de8b63'
