
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '0cb97cdb61b919ca2c601d1ff1322b3f37f58ece'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: 'latest'
