
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito-staging
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: 'a28346a1a193f42b98388074899b7026f92e8bf6'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: 'a28346a1a193f42b98388074899b7026f92e8bf6'
