
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: twito
resources:
  - celery.yaml
  - twito.yaml
  - ingress.yaml
  - service.yaml
images:
- name: twito
  newName: rg.fr-par.scw.cloud/djnd/twito
  newTag: '3fa931f1eac5c0243f5153989af5c26277f1addc'
- name: twito-frontend
  newName: rg.fr-par.scw.cloud/djnd/twito-frontend
  newTag: '3fa931f1eac5c0243f5153989af5c26277f1addc'
