apiVersion: apps/v1
kind: Deployment
metadata:
  name: twito
  labels:
    app: twito
spec:
  replicas: 1
  selector:
    matchLabels:
      app: twito
  template:
    metadata:
      labels:
        app: twito
    spec:
      initContainers:
      - name: migrate
        image: twito
        command:
          - python
          - manage.py
          - migrate
        env:
          - name: APP_ENV
            value: production
        envFrom:
          - secretRef:
              name: db-credentials
      containers:
      - name: twito
        image: twito
        ports:
        - containerPort: 5000
        env:
          - name: APP_ENV
            value: production
          - name: REDIS_PASSWORD
            valueFrom:
              secretKeyRef:
                name: redis-credentials
                key: password
        envFrom:
          - secretRef:
              name: db-credentials
      - name: twito-frontend
        image: twito-frontend
        ports:
        - containerPort: 80
        env:
          - name: APP_ENV
            value: production
