version: '3'
services:
  flask:
    build: ./api
    ports:
      - 5000:5000
    volumes:
      - ./api:/api
    environment:
      DMI_TCAT_USERNAME: admin
      DMI_TCAT_PASSWORD: boterjekul
      APP_ENV: development
      REDIS_URL: redis://redis
      DB_URL: sqlite:///twito.sqlite3
      DJANGO_SETTINGS_MODULE: settings
    entrypoint: ./run.sh

  worker:
    build: ./api
    volumes:
      - ./api:/api
    environment:
      - REDIS_URL
    command: ['celery', '-A', 'tasks', 'worker', '--loglevel=DEBUG']

  redis:
    image: redis:6-alpine
    ports:
      - 6379:6379

  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - 8081:8081

  frontend:
    build: ./frontend
    ports:
      - 8080:80
