apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: twito-db-pv-claim
  labels:
    app: twito
spec:
  storageClassName: 'scw-bssd-retain'
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
