version: '3'
services:
  flask:
    build: .
    restart: always
    ports:
      - 5000:5000
    volumes:
      - .:/code
    environment:
      - DMI_TCAT_USERNAME
      - DMI_TCAT_PASSWORD
      - APP_ENV

  worker:
    build: .
    restart: always
    volumes:
      - .:/code
    command: ['celery', '-A', 'tasks', 'worker', '--loglevel=INFO']

  redis:
    image: redis:6-alpine
    restart: always
    ports:
      - 6379:6379
